#############################################################################
# Makefile for building: gitit
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon Nov 22 18:01:41 2010
# Project:  gitit.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile gitit.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Ilibgit2/src -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/home/bry/code/cs440/gitit/libgit2/ -lgit2 -lz -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		history.cpp \
		commit.cpp \
		currentuserinfo.cpp \
		gitstatusmodel.cpp \
		configure.cpp moc_mainwindow.cpp \
		moc_history.cpp \
		moc_commit.cpp \
		moc_currentuserinfo.cpp \
		moc_gitstatusmodel.cpp \
		moc_configure.cpp
OBJECTS       = main.o \
		mainwindow.o \
		history.o \
		commit.o \
		currentuserinfo.o \
		gitstatusmodel.o \
		configure.o \
		moc_mainwindow.o \
		moc_history.o \
		moc_commit.o \
		moc_currentuserinfo.o \
		moc_gitstatusmodel.o \
		moc_configure.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		gitit.pro
QMAKE_TARGET  = gitit
DESTDIR       = 
TARGET        = gitit

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ../gitit/libgit2/libgit2.a ui_mainwindow.h ui_configure.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gitit.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile gitit.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile gitit.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/gitit1.0.0 || $(MKDIR) .tmp/gitit1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/gitit1.0.0/ && $(COPY_FILE) --parents mainwindow.h history.h commit.h currentuserinfo.h gitstatusmodel.h configure.h .tmp/gitit1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp history.cpp commit.cpp currentuserinfo.cpp gitstatusmodel.cpp configure.cpp .tmp/gitit1.0.0/ && $(COPY_FILE) --parents mainwindow.ui configure.ui .tmp/gitit1.0.0/ && (cd `dirname .tmp/gitit1.0.0` && $(TAR) gitit1.0.0.tar gitit1.0.0 && $(COMPRESS) gitit1.0.0.tar) && $(MOVE) `dirname .tmp/gitit1.0.0`/gitit1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/gitit1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


../gitit/libgit2/libgit2.a: FORCE
	make -C ../gitit/libgit2

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_history.cpp moc_commit.cpp moc_currentuserinfo.cpp moc_gitstatusmodel.cpp moc_configure.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_history.cpp moc_commit.cpp moc_currentuserinfo.cpp moc_gitstatusmodel.cpp moc_configure.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_history.cpp: history.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) history.h -o moc_history.cpp

moc_commit.cpp: commit.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) commit.h -o moc_commit.cpp

moc_currentuserinfo.cpp: currentuserinfo.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) currentuserinfo.h -o moc_currentuserinfo.cpp

moc_gitstatusmodel.cpp: gitstatusmodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gitstatusmodel.h -o moc_gitstatusmodel.cpp

moc_configure.cpp: configure.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) configure.h -o moc_configure.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_configure.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_configure.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_configure.h: configure.ui
	/usr/bin/uic-qt4 configure.ui -o ui_configure.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		gitstatusmodel.h \
		configure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

history.o: history.cpp history.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o history.o history.cpp

commit.o: commit.cpp commit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commit.o commit.cpp

currentuserinfo.o: currentuserinfo.cpp currentuserinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o currentuserinfo.o currentuserinfo.cpp

gitstatusmodel.o: gitstatusmodel.cpp gitstatusmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gitstatusmodel.o gitstatusmodel.cpp

configure.o: configure.cpp configure.h \
		ui_configure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configure.o configure.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_history.o: moc_history.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_history.o moc_history.cpp

moc_commit.o: moc_commit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_commit.o moc_commit.cpp

moc_currentuserinfo.o: moc_currentuserinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_currentuserinfo.o moc_currentuserinfo.cpp

moc_gitstatusmodel.o: moc_gitstatusmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gitstatusmodel.o moc_gitstatusmodel.cpp

moc_configure.o: moc_configure.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configure.o moc_configure.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

