nix:
  enable: false
  packages: [zlib zlib.dev]

flags:
  pandoc:
    embed_data_files: true
  gitit:
    plugins: true
  mintty:
    Win32-2-13-1: false
  sendfile:
    portable: true

packages:
- '.'
extra-deps:
- filestore-0.6.5
- recaptcha-0.1.0.4

resolver: lts-20.3
nix:
  packages: [zlib]
