flags:
  gitit:
    plugins: true
    network-uri: true
packages:
- '.'
extra-deps:
- filestore-0.6.3.3
- recaptcha-0.1.0.3
- uri-0.1.6.4
- ConfigFile-1.1.4
- hoauth2-1.7.2
- url-2.1.3
- exceptions-0.8.3
- aeson-1.3.1.1
- uri-bytestring-aeson-0.1.0.6
- skylighting-0.7.4
- skylighting-core-0.7.4
resolver: lts-12.4
