<div class="pageTools">
  <fieldset>
    <legend>This page</legend>
    <ul>
      <li><a href="$base$$pageUrl$?showraw$if(revision)$&amp;revision=$revision$$endif$">Raw page source</a></li>
      <li><a href="$base$$pageUrl$?printable$if(revision)$&amp;revision=$revision$$endif$">Printable version</a></li>
      <li><a href="$base$$pageUrl$?delete">Delete this page</a></li>
    </ul>
    $exportbox$
  </fieldset>
</div>
