<div class="sitenav">
  <fieldset>
    <legend>Site</legend>
    <ul>
      <li><a href="$base$/">Front page</a></li>
      <li><a href="$base$/_index">All pages</a></li>
      <li><a href="$base$/_categories">Categories</a></li>
      <li><a href="$base$/_random">Random page</a></li>
      <li><a href="$base$/_activity">Recent activity</a></li>
      <li><a href="$base$/_upload">Upload a file</a></li>
      <li><a href="$base$/Help">Help</a></li>
    </ul>
    $searchbox$
  </fieldset>
</div>
